### ISSUE TITLE
Differential Expression markers

### ISSUE THREAD

**Issue by alead** [keyes-timothy/classes#2]
Only compare cell subsets with the following functional markers:

- CD45RO
- GrzB
- H3K27me3
- H3K9Ac
- HO-1
- IDO
- IFNg
- Ki67
- MMP9
- PD1
- TIM3
- pS6

**Comment by alead** [comment]
> Only compare cell subsets with the following functional markers:
> 
> * CD45RO
> * GrzB
> * H3K27me3
> * H3K9Ax
> * HO-1
> * IDO
> * IFNg
> * Ki67
> * MMP9
> * PD1
> * TIM3
> * pS6

**Comment by keyes-timothy** [comment]
I'm happy to do this, and I'm running the new report with only the markers included above. That being said, most of the significant differences we originally saw were in phenotypic markers (aka not included in this list), so we will probably get relatively few hits from this list alone. If that's fine, I can proceed.

**Comment by alead** [comment]
Yep that is perfect

**Comment by keyes-timothy** [comment]
Done.
